### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by loris** [19h/pkcs7#1]
Hello @KenanSulayman 
Was wondering what is the status of this project? Have you managed to make your bindings work? Is it supposed to work for a particular version of Node.js (and bundled version of openssl) only?
I am very interested in making it work but was not successful yet.

**Comment by 19h** [comment]
@loris sorry for the delay. You can probably take the core code and easily port it to nan, as is, it won’t work

**Comment by 19h** [comment]
Actually it’s using nan, it could probably work. I’ll check it tomorrow when I’m back in the office.

**Comment by loris** [comment]
Hi Kenan Sulayman, I was writing a comment but closed the issue before.
I was able to make the bindings work taking out some code from https://github.com/MySiteApp/node-safari-push-notifications (which indeed uses `nan` thanks to you)

Thanks!
